# Demo Principal component analysis

## manually calculate principal component analysis


In [1]:
import numpy as np 
import pandas as pd

In [2]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
m = np.mean(a.T, axis=1)
m

array([3., 4.])

In [4]:
c = a-m
c

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [5]:
v = np.cov(c.T)
v

array([[4., 4.],
       [4., 4.]])

### eigendecomposition of covariance matrix

In [6]:
values, vectors = np.linalg.eig(v)
print(vectors)
print(values)
# project data
p = vectors.T.dot(c.T)
print(p.T)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
